// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/analyze": {
            "post": {
                "description": "Retrieves similar known scam patterns and asks the LLM to score the message red/yellow/green.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analyze"
                ],
                "summary": "Score a message for scam risk",
                "parameters": [
                    {
                        "description": "Message to score",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analyze.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analyzer.AnalysisResult"
                        }
                    },
                    "400": {
                        "description": "malformed body, empty text, or body too large",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    },
                    "500": {
                        "description": "retrieval or scoring failed",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    }
                }
            }
        },
        "/v1/chat": {
            "post": {
                "description": "Routes a multi-turn message into one of three flows: questions about the project, about the founder, or (default) scam detection. The last message must be from the user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat with the ChậmLại.vn assistant",
                "parameters": [
                    {
                        "description": "Conversation history",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chat.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chat.ChatResponse"
                        }
                    },
                    "400": {
                        "description": "malformed body, invalid messages, or last message not from user",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    },
                    "500": {
                        "description": "routing, retrieval, scoring, or answering failed",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analyze.Request": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "description": "Text is the suspicious message to score. Required; capped well above\nany real chat message to keep embedding/LLM cost bounded.",
                    "type": "string",
                    "maxLength": 10000
                }
            }
        },
        "analyzer.AnalysisResult": {
            "type": "object",
            "properties": {
                "disclaimer": {
                    "type": "string"
                },
                "matched_patterns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recommended_actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "red_flags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "risk_level": {
                    "description": "\"red\" | \"yellow\" | \"green\"",
                    "type": "string"
                }
            }
        },
        "chat.ChatResponse": {
            "type": "object",
            "properties": {
                "analysis": {
                    "$ref": "#/definitions/analyzer.AnalysisResult"
                },
                "intent": {
                    "$ref": "#/definitions/chat.Intent"
                },
                "reply": {
                    "type": "string"
                }
            }
        },
        "chat.Intent": {
            "type": "string",
            "enum": [
                "project",
                "founder",
                "scam"
            ],
            "x-enum-varnames": [
                "IntentProject",
                "IntentFounder",
                "IntentScam"
            ]
        },
        "chat.Request": {
            "type": "object",
            "required": [
                "messages"
            ],
            "properties": {
                "messages": {
                    "description": "Messages is the ordered conversation history, oldest first. Required and\ncapped to keep prompt size bounded.",
                    "type": "array",
                    "maxItems": 50,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/internal_api_v1_chat.Message"
                    }
                }
            }
        },
        "internal_api_v1_chat.Message": {
            "type": "object",
            "required": [
                "content",
                "role"
            ],
            "properties": {
                "content": {
                    "description": "Content is the message text. Capped to bound embedding/LLM cost.",
                    "type": "string",
                    "maxLength": 10000
                },
                "role": {
                    "description": "Role is who sent the message: \"user\" or \"assistant\".",
                    "type": "string",
                    "enum": [
                        "user",
                        "assistant"
                    ]
                }
            }
        },
        "problem.Problem": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ChậmLại.vn Scam-Scoring API",
	Description:      "RAG service that scores whether a Vietnamese message is a scam (red/yellow/green verdict).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
