// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/analyze": {
            "post": {
                "description": "Retrieves similar known scam patterns and asks the LLM to score the message red/yellow/green.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analyze"
                ],
                "summary": "Score a message for scam risk",
                "parameters": [
                    {
                        "description": "Message to score",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analyze.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/analyzer.AnalysisResult"
                        }
                    },
                    "400": {
                        "description": "malformed body, empty text, or body too large",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    },
                    "429": {
                        "description": "rate limited, or the daily budget for paid calls is exhausted",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    },
                    "500": {
                        "description": "retrieval or scoring failed",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    },
                    "503": {
                        "description": "budget could not be verified; request rejected to fail closed",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "analyze.Request": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "description": "Text is the suspicious message to score. Required; capped well above\nany real chat message to keep embedding/LLM cost bounded.",
                    "type": "string",
                    "maxLength": 5000
                }
            }
        },
        "analyzer.AnalysisResult": {
            "type": "object",
            "properties": {
                "disclaimer": {
                    "type": "string"
                },
                "matched_patterns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recommended_actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "red_flags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "risk_level": {
                    "description": "\"red\" | \"yellow\" | \"green\"",
                    "type": "string"
                },
                "sources": {
                    "description": "matched source documents backing the verdict; [] when nothing matched",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/analyzer.Source"
                    }
                }
            }
        },
        "analyzer.Source": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "problem.Problem": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ChậmLại.vn Scam-Scoring API",
	Description:      "RAG service that scores whether a Vietnamese message is a scam (red/yellow/green verdict).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
